### ISSUE TITLE
Example in Readme

### ISSUE THREAD

**Issue by mancvso** [dimparf/Soriento#1]
What's going on here?
When you define the class Blog, it contains two attributes and none of them is content.

``` scala
//...
val blog = Blog("Dim", content = Message("Hi"))
//...
```

should read

``` scala
//...
val blog = Blog("Dim", message = Message("Hi"))
//...
```

Or if you want to leverage some semantics, maybe the case class has to be defined

``` scala
case class Blog(author: String, @Embedded content: Message)
```

**Comment by dimparf** [comment]
Hi, mancvso
Thank you for look at this. This is bug in README.
It must be case class Blog(author: String, @Embedded message: Message).
I am fix it.
