### ISSUE TITLE
Create macros for generate ODocumentReader[T]'s

### ISSUE THREAD

**Issue by dimparf** [dimparf/Soriento#4]

**Comment by b0c1** [comment]
Hi dude, I created the first version of ODocumentReader library, this is using reflection, but all test is work. 
https://github.com/b0c1/Soriento/commit/f7a6a5c2ca7b4a601f8e0f7d74af6cbcfda8653f

**Comment by dimparf** [comment]
Hi b0c1, Your work is great. I accept your merge request (if you create it). Our library need more tests, not all cases tested.
And I add You to contributors:)

**Comment by b0c1** [comment]
Pull request sent :)

**Comment by dimparf** [comment]
Congrats!
